-- Hermod schema (PostgreSQL flavour).
--
-- Functional parity with `migrations/20260425000001_initial.sql` (the
-- SQLite flavour). Differences are dialect-only:
--
--   * `BLOB`              → `BYTEA`
--   * `INTEGER`           → `BIGINT`         (millisecond timestamps + i64s)
--   * `INTEGER PRIMARY KEY AUTOINCREMENT`
--                         → `BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
--   * `REAL`              → `DOUBLE PRECISION`
--   * `GENERATED ALWAYS AS (…) VIRTUAL`
--                         → `GENERATED ALWAYS AS (…) STORED`
--   * `0 / 1` boolean encoded columns kept as `BIGINT` (not `BOOLEAN`)
--     so row decoders are bit-for-bit identical across backends.
--
-- Functional invariants that MUST hold across both flavours:
--   * Column names + ordering identical (so a single decoder reads from
--     either backend).
--   * `CHECK` constraints identical.
--   * Index names identical (so operator runbooks and EXPLAIN output
--     read the same).
--   * Partial indexes' `WHERE` predicates identical — Postgres supports
--     them natively.

CREATE TABLE agents (
    id                  TEXT NOT NULL PRIMARY KEY,
    pubkey              BYTEA NOT NULL,
    host_pubkey         BYTEA,
    endpoint            TEXT,
    -- Mirrors sqlite migration; see comment there for semantics.
    via_agent        TEXT REFERENCES agents(id) ON DELETE SET NULL,
    local_alias         TEXT UNIQUE,
    peer_asserted_alias TEXT,
    trust_level         TEXT NOT NULL
                        CHECK (trust_level IN ('local','verified','tofu','untrusted')),
    tls_fingerprint     TEXT,
    reputation          BIGINT NOT NULL DEFAULT 0,
    first_seen          BIGINT NOT NULL,
    last_seen           BIGINT,
    -- See sqlite migration for column purpose. Postgres parity.
    peer_asserted_tags  TEXT NOT NULL DEFAULT '[]',
    CHECK (endpoint IS NULL OR via_agent IS NULL)
);
CREATE INDEX idx_agents_with_endpoint ON agents(id) WHERE endpoint IS NOT NULL;

CREATE TABLE local_agents (
    agent_id            TEXT NOT NULL PRIMARY KEY
                        REFERENCES agents(id) ON DELETE CASCADE,
    bearer_hash         BYTEA NOT NULL,
    workspace_root      TEXT,
    created_at          BIGINT NOT NULL,
    -- See sqlite migration for column purpose. Postgres parity.
    tags                TEXT NOT NULL DEFAULT '[]'
);
CREATE UNIQUE INDEX idx_local_agents_bearer_hash ON local_agents(bearer_hash);

CREATE TABLE messages (
    id              TEXT NOT NULL PRIMARY KEY,
    thread_id       TEXT,
    from_agent      TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    to_agent        TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    kind            TEXT NOT NULL,
    priority        TEXT NOT NULL,
    body_json       TEXT NOT NULL,
    envelope_cbor   BYTEA NOT NULL,
    status          TEXT NOT NULL
                    CHECK (status IN ('pending','delivered','read','expired','failed')),
    attempts        BIGINT NOT NULL DEFAULT 0,
    next_attempt_at BIGINT,
    claim_token     TEXT,
    claimed_at      BIGINT,
    created_at      BIGINT NOT NULL,
    delivered_at    BIGINT,
    read_at         BIGINT,
    expires_at      BIGINT,
    file_blob_location TEXT,
    delivery_endpoint TEXT,
    -- See sqlite migration for column purpose. Postgres parity.
    disposition     TEXT NOT NULL DEFAULT 'push'
                    CHECK (disposition IN ('push','silent'))
);
CREATE INDEX idx_messages_inbox ON messages(to_agent, status, created_at);
CREATE INDEX idx_messages_pushed_inbox
    ON messages(to_agent, disposition, status, created_at);
CREATE INDEX idx_messages_thread ON messages(thread_id, created_at);
CREATE INDEX idx_messages_expiry ON messages(expires_at)
    WHERE status IN ('pending','delivered');
CREATE INDEX idx_messages_outbox ON messages(next_attempt_at)
    WHERE status = 'pending' AND delivery_endpoint IS NOT NULL;
CREATE INDEX idx_messages_outbox_claim ON messages(claimed_at)
    WHERE status = 'pending' AND claim_token IS NOT NULL;

CREATE TABLE capabilities (
    id            TEXT NOT NULL PRIMARY KEY,
    issuer        TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    audience      TEXT,
    scope         TEXT NOT NULL,
    target        TEXT,
    expires_at    BIGINT,
    revoked_at    BIGINT,
    raw_token     BYTEA NOT NULL,
    direction     TEXT NOT NULL DEFAULT 'issued'
                  CHECK (direction IN ('issued','received'))
);

CREATE TABLE audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            BIGINT NOT NULL,
    actor         TEXT NOT NULL,
    action        TEXT NOT NULL,
    target        TEXT,
    details_json  TEXT,
    client_ip     TEXT,
    prev_hash     BYTEA NOT NULL,
    row_hash      BYTEA NOT NULL,
    sig           BYTEA NOT NULL
);
CREATE INDEX idx_audit_actor_ts ON audit_log(actor, ts);
CREATE INDEX idx_audit_ts ON audit_log(ts);

CREATE TABLE rate_buckets (
    pair_key      TEXT NOT NULL PRIMARY KEY,
    tokens        DOUBLE PRECISION NOT NULL,
    updated_at    BIGINT NOT NULL
);

CREATE TABLE briefs (
    agent_id      TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    topic         TEXT,
    summary       TEXT NOT NULL,
    published_at  BIGINT NOT NULL,
    expires_at    BIGINT,
    topic_key     TEXT GENERATED ALWAYS AS (COALESCE(topic, '')) STORED,
    UNIQUE (agent_id, topic_key)
);
CREATE INDEX idx_briefs_published ON briefs(agent_id, published_at);

CREATE TABLE agent_presence (
    agent_id                  TEXT NOT NULL PRIMARY KEY REFERENCES agents(id) ON DELETE CASCADE,
    manual_status             TEXT CHECK (manual_status IN ('online','idle','busy','offline')),
    manual_status_set_at      BIGINT,
    manual_status_expires_at  BIGINT,
    peer_live                 BIGINT CHECK (peer_live IN (0, 1)),
    peer_live_updated_at      BIGINT,
    peer_live_expires_at      BIGINT
);

-- See sqlite migration for column-purpose detail. Postgres parity:
-- partial unique index uses `WHERE session_label IS NOT NULL`,
-- equivalent semantics to the sqlite expression.
CREATE TABLE mcp_sessions (
    session_id            TEXT NOT NULL PRIMARY KEY,
    agent_id              TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    session_label         TEXT,
    attached_at           BIGINT NOT NULL,
    last_heartbeat_at     BIGINT NOT NULL,
    client_name           TEXT,
    client_version        TEXT,
    last_message_id       TEXT,
    last_confirmation_id  TEXT,
    last_resolved_seq     BIGINT
);
CREATE INDEX idx_mcp_sessions_heartbeat ON mcp_sessions(last_heartbeat_at);
CREATE INDEX idx_mcp_sessions_agent ON mcp_sessions(agent_id, last_heartbeat_at);
CREATE UNIQUE INDEX idx_mcp_sessions_agent_label
    ON mcp_sessions(agent_id, session_label) WHERE session_label IS NOT NULL;

CREATE TABLE workspaces (
    id              TEXT NOT NULL PRIMARY KEY,
    name            TEXT NOT NULL,
    visibility      TEXT NOT NULL
                    CHECK (visibility IN ('public','private')),
    secret          BYTEA,
    created_locally BIGINT NOT NULL DEFAULT 0
                    CHECK (created_locally IN (0, 1)),
    muted           BIGINT NOT NULL DEFAULT 0
                    CHECK (muted IN (0, 1)),
    joined_at       BIGINT NOT NULL,
    last_active     BIGINT
);

CREATE TABLE channels (
    id            TEXT NOT NULL PRIMARY KEY,
    workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    mac_key       BYTEA,
    muted         BIGINT NOT NULL DEFAULT 0
                  CHECK (muted IN (0, 1)),
    joined_at     BIGINT NOT NULL,
    last_active   BIGINT,
    UNIQUE (workspace_id, name)
);
CREATE INDEX idx_channels_workspace ON channels(workspace_id);

CREATE TABLE workspace_members (
    workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    agent_id      TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    first_seen    BIGINT NOT NULL,
    last_seen     BIGINT,
    PRIMARY KEY (workspace_id, agent_id)
);

CREATE TABLE channel_messages (
    id            TEXT NOT NULL PRIMARY KEY,
    channel_id    TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    from_agent    TEXT NOT NULL,
    body_text     TEXT NOT NULL,
    received_at   BIGINT NOT NULL
);
CREATE INDEX idx_channel_messages_channel ON channel_messages(channel_id, received_at);

CREATE TABLE pending_confirmations (
    id            TEXT NOT NULL PRIMARY KEY,
    envelope_id   TEXT NOT NULL,
    requested_at  BIGINT NOT NULL,
    actor         TEXT NOT NULL,
    recipient     TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    intent        TEXT NOT NULL,
    sensitivity   TEXT NOT NULL
                  CHECK (sensitivity IN ('routine','review','sensitive')),
    trust_level   TEXT NOT NULL,
    summary       TEXT NOT NULL,
    envelope_cbor BYTEA NOT NULL,
    status        TEXT NOT NULL
                  CHECK (status IN ('pending','accepted','rejected','expired'))
                  DEFAULT 'pending',
    decided_at    BIGINT,
    decided_by    TEXT
);
CREATE INDEX idx_pending_confirmations_status
    ON pending_confirmations(status, requested_at);
CREATE INDEX idx_pending_confirmations_recipient
    ON pending_confirmations(recipient, status, requested_at);
CREATE UNIQUE INDEX idx_pending_confirmations_envelope_pending
    ON pending_confirmations(envelope_id) WHERE status = 'pending';

CREATE TABLE audit_archive_index (
    epoch_start      BIGINT NOT NULL PRIMARY KEY,
    epoch_end        BIGINT NOT NULL,
    first_row_id     BIGINT NOT NULL,
    last_row_id      BIGINT NOT NULL,
    row_count        BIGINT NOT NULL,
    first_prev_hash  BYTEA NOT NULL,
    last_row_hash    BYTEA NOT NULL,
    blob_location    TEXT NOT NULL,
    file_size        BIGINT NOT NULL,
    archived_at      BIGINT NOT NULL,
    manifest_sig     BYTEA NOT NULL
);
CREATE INDEX idx_audit_archive_index_archived
    ON audit_archive_index(archived_at);

-- See sqlite migration for column-purpose detail. Postgres parity.
CREATE TABLE notifications (
    id                  TEXT NOT NULL PRIMARY KEY,
    recipient_agent_id  TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    message_id          TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    status              TEXT NOT NULL
                        CHECK (status IN ('pending','dispatched','failed','dismissed')),
    sound               TEXT,
    attempts            BIGINT NOT NULL DEFAULT 0,
    claim_token         TEXT,
    claimed_at          BIGINT,
    dispatched_at       BIGINT,
    failed_reason       TEXT,
    created_at          BIGINT NOT NULL
);
CREATE INDEX idx_notifications_dispatch
    ON notifications(recipient_agent_id, status, created_at);

CREATE TABLE discovered_channels (
    workspace_id   TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    channel_id     TEXT NOT NULL,
    channel_name   TEXT NOT NULL,
    advertised_by  TEXT NOT NULL,
    discovered_at  BIGINT NOT NULL,
    last_seen      BIGINT NOT NULL,
    PRIMARY KEY (workspace_id, channel_id)
);
CREATE INDEX idx_discovered_channels_seen ON discovered_channels(last_seen);

CREATE TABLE schema_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
INSERT INTO schema_meta (key, value) VALUES ('version', '1');
